language: python
python:
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "pypy3"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=trade -m unittest discover tests
after_success:
  coveralls
branches:
  only:
    - master
